spring.application.name=chatMe

spring.datasource.url=jdbc:mysql://chat-me-sandeepmishra898k-33ec.a.aivencloud.com:11802/chatme
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}